### ISSUE TITLE
Bug: Slider range not perfectly aligned with the track

### ISSUE THREAD

**Issue by Horsetoast** [radix-ui/design-system#388] opened 2023-12-19 04:40 UTC
The Slider component has a small visual issue. When the track is close to the left side, the right edge of the range bar appears before the left edge of the range track. This issue is only visible when the slider height is a bit bigger, so I increased the height in the [radix example](https://www.radix-ui.com/primitives/docs/components/slider) to showcase the problem

Here is where the problem is visible:
<img width="240" alt="Screenshot 2023-12-19 at 11 31 01" src="https://github.com/radix-ui/design-system/assets/4919815/ab21ab39-ec0a-4634-841b-c72fd29bd007">

When the track is closer to the right side, the range and track looks aligned (as it should be):
<img width="245" alt="Screenshot 2023-12-19 at 11 31 10" src="https://github.com/radix-ui/design-system/assets/4919815/12f40618-a96e-4cf2-a3e7-9be04ddb1564">

**Comment by vladmoroz** [comment] 2023-12-19 09:41
This is a duplicate of https://github.com/radix-ui/primitives/issues/1966, please refer to that issue

**Closed by vladmoroz** 2023-12-19 09:41 UTC
